### ISSUE TITLE
Add support to change email

### ISSUE THREAD

**Issue by 1rV1N-git** [MoneroOcean/nodejs-pool#10]
Hello
Please add support to change email in settings after login.

app.js
```javascript
secureRoutes.post('/changeEmail', function (req, res) {
      global.mysql.query("UPDATE users SET email = ? WHERE id = ?", [req.body.email, req.decoded.id]).then(function () {
        return res.json({'msg': 'Email updated, set to: ' + req.body.email});
    });
});
```

**Comment by MoneroOcean** [comment]
Done: https://github.com/MoneroOcean/nodejs-pool/commit/748f2126d4c8b8ebb362d14430599a995f63a784

**Comment by bobbieltd** [comment]
I really hate the login with email as password. It’s really weird.

**Comment by bobbieltd** [comment]
Thanks both for added feature 👍

**Comment by 1rV1N-git** [comment]
@MoneroOcean  thank you very much!!
