### ISSUE TITLE
Pool module crash when miner trust is disabled

### ISSUE THREAD

**Issue by JPaulMora** [MoneroOcean/nodejs-pool#100]
https://github.com/MoneroOcean/nodejs-pool/blob/b6ac358ec5939a1a1bb202860807507248c4b318/lib/pool.js#L1370

There is an issue where the pool module crashes when printing this line due to miner.trust.trust not being defined if `trustedMiners` is set to false in database.

**Comment by MoneroOcean** [comment]
Thank you! Fixed in 2ff89f0ff004bb59ebdb92e93d6ce9b5e0f0f4ff
