### ISSUE TITLE
[Feature Request]: Merged Mining Altcoins with same algo

### ISSUE THREAD

**Issue by setuidroot** [MoneroOcean/nodejs-pool#107]
Is it possible to merge mine altcoins that use the same mining algorithms?  I know MO pool has done this in the past (with old cn-pico/trtl if I remember correctly.)

I was thinking of merged mining **cn/r** (SUMO and LTHN) and **cn/gpu** (RYO and XEQ) maybe even **c29s** (XWP and XTNC.)  Although I'm not sure the latter is worth the effort.  Nor do I think cn/r is worth the time, that is ASIC controlled algo now and most people know this.  I think only old bots that are unable to push miner updates still mine cn/r.

I am mostly talking about **cn/gpu** (RYO and XEQ) these two together would be good for miner profitability and it would help MO pool with more trading fee deltas.  I don't see why merged mining of these two coins would not be possible.  Maybe impossible if the algorithm has different iterations or something I don't know about.

I don't understand merged mining ~~very well~~ at all.  My conceptual understanding of it is that miners mine the algorithm (cn/gpu) and then pool picks share results with a high enough difficulty to solve a block on either RYO or XEQ.  Maybe a high enough difficulty share can be used to solve a block on both networks?  It seems like this would be possible with a mining proxy.

Pool runs RYO and XEQ daemons.

XNP proxy gives "blank" work (block) template to miners asking for CN/GPU results.

If XNP proxy gets a share with a high enough difficulty to solve a block on RYO and/or XEQ; then it passes that share to pool with RYO and/or XEQ block template.  I guess you cannot add block templates after the fact?  Can XNP proxy give work templates for both coins?

**Example**:

Say RYO network difficulty is higher than XEQ's network diff.

XNP (MO proxy) gets a share with a high enough diff to solve XEQ, but not RYO: it gives pool block to post to XEQ network.

XNP gets a share with a high enough diff to solve both networks: either post blocks to both RYO and XEQ **or** (if cannot do both) post the solving share to whichever coin network's block reward is worth more Monero.

XNP gets valid shares too low to solve block on either network: obviously just discard, but credit the miner who sent it to the pool.

**Summary**:

I would like to merge mine cn/gpu algo altcoins RYO and XEQ on MO pool.  Maybe this isn't possible.  Maybe it is possible, but not worth the effort.  Maybe pool already does this to help support 0% pool fee.  For sure I don't really understand what I'm talking about lol.

Sorry to post questions here... this isn't an issue.  Maybe better off to post on Reddit, but Monero people will downvote me for talking about altcoins lol.  It's just an idea anyways.

**Comment by MoneroOcean** [comment]
In addition to the same PoW merge mining is only possible if one of coins has "forknote" blob type (if block header can contain parent block). Other coin can have any blob type. From all coins pool support now only TRTL and IRD coins has forknote blob type. So now I do not see any coin that can be merge mined (from the coins that pool support).

**Comment by setuidroot** [comment]
Okay, thanks for the answer.
