### ISSUE TITLE
Cmake Release Failed

### ISSUE THREAD

**Issue by Craftoncu** [MoneroOcean/nodejs-pool#112]
-- Checking submodules
CMake Error at CMakeLists.txt:203 (message):
  Submodule 'external/miniupnp' is not up-to-date.  Please update all
  submodules with

  git submodule update --init --force

  or run cmake with -DMANUAL_SUBMODULES=1

Call Stack (most recent call first):
  CMakeLists.txt:208 (check_submodule)

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/monero/build/release/CMakeFiles/CMakeOutput.log".
Makefile:91: recipe for target 'cmake-release' failed
make: *** [cmake-release] Error 1
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- CMake version 3.5.1
-- ccache NOT found! Please install it for faster rebuilds.
-- Building without build tag
-- Checking submodules
CMake Error at CMakeLists.txt:203 (message):
  Submodule 'external/miniupnp' is not up-to-date.  Please update all
  submodules with

  git submodule update --init --force

  or run cmake with -DMANUAL_SUBMODULES=1

Call Stack (most recent call first):
  CMakeLists.txt:208 (check_submodule)

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/monero/build/release/CMakeFiles/CMakeOutput.log".
Makefile:91: recipe for target 'cmake-release' failed
make: *** [cmake-release] Error 1

**Comment by Craftoncu** [comment]
Plain Ubuntu 16.04
Running under user monero in sudo group (pw less)

**Comment by tjenikovsky** [comment]
I confirm this issue, I am facing the same problem.
Tried on clear installation of Ubuntu 18.04.

**Comment by seoseo29** [comment]
deploy.bash

cd ~
git clone https://github.com/MoneroOcean/nodejs-pool.git
sudo systemctl enable ntp
cd /usr/local/src
sudo git clone --recursive https://github.com/monero-project/monero.git
cd monero
sudo git checkout v0.17.1.9
cd external/
sudo rm -rf ./miniupnp/
sudo git clone https://github.com/monero-project/miniupnp
cd ..
sudo git submodule update --init --force
