### ISSUE TITLE
RVN config Last block header request for 8766 port failed

### ISSUE THREAD

**Issue by seoseo29** [MoneroOcean/nodejs-pool#113]
Hey! how to set up RVN?
Changed in /home/user/nodejs-pool/lib/coins/xmr.js
    "16000": "CCX",
    "8766": "",
    "8545": "ETH",

In msql port 8766
Installed RVN wallets

In /home/user/.raven/raven.conf

prune = 550
daemon = 1
addnode = 39.108.143.132
addnode = 158.69.141.235

I get a pool log error
7 | pool | 2021-03-02 08: 49: 19: 237 +00: 00: "JSON parse exception:"
7 | pool | 2021-03-02 08: 49: 19: 237 +00: 00: (Worker 9 - 20822) Last block header request for 8766 port failed!
7 | pool | 2021-03-02 08: 49: 19: 291 +00: 00: "JSON parse exception:"
7 | pool | 2021-03-02 08: 49: 19: 292 +00: 00: (Master) Last block header request for 8766 port failed!
7 | pool | 2021-03-02 08: 49: 19: 356 +00: 00: "JSON parse exception:"
7 | pool | 2021-03-02 08: 49: 19: 357 +00: 00: Archor last block header request failed!
7 | pool | 2021-03-02 08: 49: 19: 423 +00: 00: "JSON parse exception:"
7 | pool | 2021-03-02 08: 49: 19: 423 +00: 00: (Worker 20 - 20935) Last block header request for 8766 port failed!

**Comment by MoneroOcean** [comment]
Support for open source part of the pool is only provided for XMR.
