### ISSUE TITLE
Total due increase feature request (by AI)

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#13]
If possible, can you add next total due increase with more sophicated Artificial Intelligence and Probability ? It helps the pool when it hits bad luck.

**Comment by MoneroOcean** [comment]
I doubt any AI can predict future since there is no dependency of next block effort based on previous effort distribution.

**Comment by bobbieltd** [comment]
Yeah, I don’t think it’s not possible but at least we need a solution for longtime unincreased total due. It’s not good for small pools. Can we make a hybrid model ( PPLNS + PPS ), for example PPLNS 90% + PPS 10% ? It’s more feasable.

**Comment by MoneroOcean** [comment]
Imagine how fun it will be to explain people this hybrid payment system. Even plain PPLNS cause issues to understand this. Also I'm not aware of any pool including other coins that use something like this.
