### ISSUE TITLE
Can you add pplnsShares: Number(cachedData.shares) to API (for front-end to calculate rewards estimation) ?

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#14]
return callback(null, {hash: cachedData.hash, identifier: 'global', lastHash: Math.floor(cachedData.lastHash / 1000), totalHashes: cachedData.totalHashes, validShares: Number(cachedData.goodShares), invalidShares: Number(cachedData.badShares)});
--> to add pplnsShares: Number(cachedData.shares)

Thank you for your consideration.

**Comment by MoneroOcean** [comment]
OK, I will look into it (but do not promise it soon).
