### ISSUE TITLE
So sad, I can’t follow your codes with multi coins

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#15]
Hix, it looks complicated now. If possible, can you maintain two repos, one old repo for only one coin, one repo for multiple coins. I love your codes but it becomes too hard for me now :((. Thanks for your great work.

**Comment by MoneroOcean** [comment]
Unfortunately I do not have plans to main two repos because I do not want to put resources on codes that I do not run myself on my pool. On slightly positive note multi coin support should not break existing mono coin pool (at least transition to it worked smoothly in my case).

**Comment by bobbieltd** [comment]
I wait and see your new innovative pool. Very good idea even I think it’s bad in practice. In the mean time, I try to research Ethereum (Ethash) pool. Keep doing your code improvements 👍. I’ll be back !
