### ISSUE TITLE
Email schedule feature

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#19]
I’d like to have email merge feature so the miners will receive payments report once or twice per day (with payments and time of that payments). It’s mainly for small shit coins that low hashrate miners receive many payments.
Thanks MoneroOcean.
Very low priority ( I can disable or make payment interval higher to reduce emails as a workaround)

**Comment by bobbieltd** [comment]
By the way, worker stop/start hashing should be merged per hour or two hours (I still have problem with this scary emails).

**Comment by 1rV1N-git** [comment]
@bobbieltd about start\stop. 
Change hashrate_avg_min to min 7 or more. it is because xmrig have donate time default 5 min and hashrate_avg_min = 5 min.

**Comment by MoneroOcean** [comment]
I do not think it is a big problem with xmrig. At least nobody complained yet. Do you have such reports from miners?

**Comment by bobbieltd** [comment]
@1rV1N-git Thanks for info. I'll take a look.
@MoneroOcean I have no complaint (I don't know about other pools). It's just my feeling that it's bad if we send stop/start hashing because the miners don't miner for some minutes.

**Comment by MoneroOcean** [comment]
Returned 10 mins here: https://github.com/MoneroOcean/nodejs-pool/commit/4e1ef3baa91e500c80e4c77929f58f6c5bc6aa19

**Comment by bobbieltd** [comment]
Updated all workers to 10 mins. Thank you both.
