### ISSUE TITLE
long runner

### ISSUE THREAD

**Issue by 1rV1N-git** [MoneroOcean/nodejs-pool#2]
Hello

This code don't get oldest locked block. it gets first random locked blocks.
If you have some unlocked block, it can be problem.
I think this need to get all unlocked blocks sort it by "timestamp" then get oldest.

 this.getOldestLockedBlock = function(){
    this.refreshEnv();
    debug("Getting the oldest locked block in the system");
    let txn = this.env.beginTxn({readOnly: true});
    let cursor = new this.lmdb.Cursor(txn, this.blockDB);
    let highestBlock = null;
    for (let found = cursor.goToFirst(); found; found = cursor.goToNext()) {
        if (highestBlock !== null){
            break;
        }
        cursor.getCurrentBinary(function(key, data){  // jshint ignore:line
            let blockData = global.protos.Block.decode(data);
            if (blockData.unlocked === false){
                highestBlock = blockData;
            }
        });
    }
    cursor.close();
    txn.commit();
    if (highestBlock !== null) {
        debug("Got the oldest locked block in the system at height: " + JSON.stringify(highestBlock));
    } else {
        debug("There are no unlocked blocks in the system.  Woohoo!");
    }
    return highestBlock;
};

I told Snipa22, but he say it isn't promlem
https://github.com/Snipa22/nodejs-pool/issues/227

Can you write what i offered?
Thanks

**Comment by MoneroOcean** [comment]
So the problem is that it can remove shares that are still required for payment calculations, right?

**Comment by 1rV1N-git** [comment]
yes
for pplns too

**Comment by MoneroOcean** [comment]
I actually also have reports that it can happen from hashvault pool operator as well, so I believe there must be something wrong with this or related code. Maybe not in the getOldestLockedBlock function but later. Will take a closer look.

**Comment by MoneroOcean** [comment]
Or maybe do you have debug info? You mentioned that the problem was detected by you in this line:

`callback(null, body.height - Math.floor(global.config.payout.blocksRequired/2), Math.floor(body.difficulty * global.config.pplns.shareMulti * 5));`

This is actually PPS case, right? And it really does not depend on oldestLockedBlock.height here, so can you please provide more observations if possible?

**Comment by 1rV1N-git** [comment]
Sorry i have 
            function(oldestLockedBlock, callback){
                global.coinFuncs.getLastBlockHeader(function(err, body){
                    if (oldestLockedBlock === null){
                        /*
                        If there's no locked blocks, then allow the system to scan from the PPS depth downwards if PPS
                        is enabled.
                        Save enough shares so that the diff * share multi * 30% for buffer.
                         */
                        if (global.config.pps.enable){
                            // If PPS is enabled, we scan for new blocks at cur height - blocksRequired/2.
                            // We need to save shares back that far at the least.
                            callback(null, body.height - Math.floor(global.config.payout.blocksRequired/2), Math.floor(body.difficulty * global.config.pplns.shareMulti * 5));
                        } else {
                            // Otherwise, we can just start from the current height.  Woo!
                            callback(null, body.height, Math.floor(body.difficulty * global.config.pplns.shareMulti * 5));
                        }

                    } else {
                        /*
                        Otherwise, start the scan from the oldest locked block downwards.
                        This protects against the blockManager being messed up and not unlocking blocks.
                        This will ensure that enough shares are in place to unlock all blocks.
                        If the block is Solo, PPLNS or PPS, it doesn't matter.
                         */
                        if (global.config.pps.enable && oldestLockedBlock.height > body.height - Math.floor(global.config.payout.blocksRequired/2)) {
                            // If PPS is enabled, and the oldestLockedBlock.height > the PPS minimum, start from the PPS minimum.
                            callback(null, body.height - Math.floor(global.config.payout.blocksRequired/2), Math.floor(body.difficulty * global.config.pplns.shareMulti * 5));
                        } else {
                            // If PPS isn't enabled, or the oldestLockedBlock.height < the PPS minimum, then start from there.
                            **callback(null, oldestLockedBlock.height, Math.floor(oldestLockedBlock.difficulty * global.config.pplns.shareMulti * 5));**
                        }
                    }
                });
            },
I have pplns mode enabled
and there were a couple of times so that there were 15 blocks locked and it took the block in the middle and counted the buffer and the rest was removed and the pplns payment passed with 0%

**Comment by MoneroOcean** [comment]
Thanks! That's definitely helpful.

**Comment by MoneroOcean** [comment]
I put guards for that issue (it does not belong to performance critical path, so it is OK to have to extra check here) and some additional related fixes to avoid important share removal:

https://github.com/MoneroOcean/nodejs-pool/commit/5ae1401710f6b64a38e46ec269d07c3f3748dd39

I already applied that to MoneroOcean pool. Nothing bad happened at least after the first share cleanup.

**Comment by 1rV1N-git** [comment]
Cool thanks. I try it.
