### ISSUE TITLE
Zone117x node-cryptonote-pool syntax support

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#20]
Hi MO !

   Some miners use syntax from other pools of which syntax is different. Can you add support for that syntax too ? It means the pool will accept two syntaxs from zone117x's repo and Snipa's repo.

Thanks.

**Comment by MoneroOcean** [comment]
Can you please give more details about that (or there to see the difference)?

**Comment by bobbieltd** [comment]
My mistake, sorry. It’s not original syntax from zone117x. Let’s take some big pools to add syntax.
MineXMR : WALLET.payID.workerID+DIFF as username
Nanopool : ADDRESS.PAYMENT-ID.WORKER/EMAIL

I think we should add one more syntax : address.paymentid.worker/email+fix diff

**Comment by MoneroOcean** [comment]
Nodejs pools already support address.worker/email+fix format (worker/email instead of paymentid). Adding support address.paymentid.worker/email+fix just to support paymentid is not very productive especially after addition of subaddresses which will make paymentid obsolete.

**Comment by bobbieltd** [comment]
Cool, I didn’t know that it already supported. Thanks for info. Close issue.
