### ISSUE TITLE
Wrong number of connections 

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#21]
I don’t know if you experience with Monero hfv7. When some one mines with wrong algo, it seems that connection is always shown up on pool connections number and won’t be decreased even that miner is off.

**Comment by MoneroOcean** [comment]
Never payed any attention to these connection numbers... OK will look into this when I will have more time.

**Comment by MoneroOcean** [comment]
I think I fixed it by https://github.com/MoneroOcean/nodejs-pool/commit/0219ee4bdee13feba5813b9acfd779280bbbdfd3
Could you please confirm?

**Comment by bobbieltd** [comment]
Oufff, it is related to #19 , changing to 10 minutes make number of connections a lot. I reverted all changes (unknown effect with high alive connections)
![ba36b07d-b455-46e9-8f8e-c6e8ae10107b](https://user-images.githubusercontent.com/29669374/39338594-e51b77de-49ed-11e8-919f-789478ba220e.jpeg)
![fbc20807-ae80-45b7-9674-60b3b86bed10](https://user-images.githubusercontent.com/29669374/39338599-ed9d9eaa-49ed-11e8-91c8-e1c5638b24c9.jpeg)

**Comment by bobbieltd** [comment]
Weird ! Restart worker doesn’t reduce those connections. So, it’s the coincidence. It seems pool codes still keeping alive connections. Hix. 😢

**Comment by bobbieltd** [comment]
It could be mysql connection issue. By somehow, on some servers, mysql variables returned to default ( auto update with new defaults or something ).

**Comment by bobbieltd** [comment]
I guess you already fixed it. Recent high connections came from users' testing XNPs. I will reopen it when I find out more.
