### ISSUE TITLE
Database explosion - longRunner possible bug.

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#22]
It’s only my theory that there is a bug in longRunner with troublesome network. I guess it won’t happen with Monero because Monero network with high hashrate and stable.

In theory, block with higher number will have timestamp higher. For example, block m and block n, if m>n, timestamp of block m will > timestamp of block n.
With pool forking (turtlecoin case), it makes two thing, two blocks with same height but different timestamp (one correct and one forked).
With timestamp attacks (turtlecoin and graft cases), block lower have higher timestamp.

By somehow, with these hapenning, database at my pools keep growing, turtlecoin (21G) and graft(24G).
If you have free time or find something in the future, I hope you can help to fix this.

**Comment by bobbieltd** [comment]
For pools is tiny, ~ 10 miners, number of shares are small. So Gb means abnormal.

**Comment by MoneroOcean** [comment]
This pool db abnormal increase happens in vanilla Snipa pool code as well. It happens when you restart worker module in the middle of DB transaction (read or write, I'm not sure). DB increase is not very harmful since basically it only increase DB size by 0 up to 24GB and this can be later reverted by using mdb_copy with shrink option. Also this increase do not really consume space in share table so it really only increase number of free page in DB.

**Comment by bobbieltd** [comment]
Thank for your info (I’ll keep an eye on your finding). Now I understand better for Graft case. Graft block time is 2 minutes. But it is under attacks and block time is 5 hours or more. So, 1 block shares database is equal 150 normal blocks. So the pool will record huge amount of shares. Database explosion to limit.

**Comment by MoneroOcean** [comment]
Do not worry about DB explosions. If you use share accumulator code then you can fit around 2 weeks of shares for MO size pool in 24 GB without much problems.

**Comment by 1rV1N-git** [comment]
@bobbieltd You can decrease max size.
change this 
 this.initEnv = function(){
        global.database.env = new this.lmdb.Env();
        global.database.env.open({
            path: global.config.db_storage_path,
            maxDbs: 10,
            mapSize: **24** * 1024 * 1024 * 1024,

if you change to 4
then 
but you after this you need to dump base msb_dump -f dump -a pool_db
and edit file dump 
change all mapsize to 4294967296 
then msb_load -f dump pool_db_new

**Comment by MoneroOcean** [comment]
I do not know enough about LMDB internals to provide fix for this DB implosion that happens sometimes due to worker module restart. Hence the mark wontfix. But let this issue be open.

**Comment by sevendoorknobs** [comment]
@1rV1N-git When you dumped your DB was it the original size or was it smaller?

**Comment by bobbieltd** [comment]
@1rV1N-git Thanks for your help, I already try to tweak local commit for DB open size limit.
I run into this big database growing again when ETN got attacked with block time > 2 hours. But when block time comes back to normal, the database get back to normal. So I guess the problem happens when block time is abnormal.

**Comment by sevendoorknobs** [comment]
#43 Had a similar issue and the commit on that thread fixed it.
