### ISSUE TITLE
Feature Request: Add All-Coins tab to the Blocks page

### ISSUE THREAD

**Issue by mefenlon** [MoneroOcean/nodejs-pool#24]
It would be nice if the blocks page
https://moneroocean.stream/#/blocks
defaulted to a tab that showed a list of all coins that have been mined.  Similar to the ALT-COINS tab but with XMR included. This would offer some insight on how the pool is moving to each coin.

**Comment by MoneroOcean** [comment]
Will consider this. But it is not simple thing since now XMR (main coin) and other coins were stored in separate tables, so I will have to modify pool API as well for that.
