### ISSUE TITLE
Feature Request: Altcoin Profitability

### ISSUE THREAD

**Issue by caradex** [MoneroOcean/nodejs-pool#25]
It would be nice to see the profitability of the altcoins in the page. We know that the pool auto-switches to them when they are at least 20% more profitable than XMR but we don't know the actual percentage when it happens. It is just good to know that we are switching to GRFT for example because it is 50% more profitable.

**Comment by MoneroOcean** [comment]
Thanks for good idea. I have something like that in mind, but not implemented it so far since it will require changes in pool API and GUI which is not quite trivial thing.

**Comment by MoneroOcean** [comment]
It was implemented on new coins page.
