### ISSUE TITLE
Installation error at patching monero daemon

### ISSUE THREAD

**Issue by mxjoe** [MoneroOcean/nodejs-pool#26]
Hi,

I tried to install monoeroocean's nodejs-pool on Ubuntu 16.04.4 several times the past days but it always comes with an error when trying to patch the monero deamon with following code:
`curl https://raw.githubusercontent.com/MoneroOcean/nodejs-pool/master/deployment/monero_daemon.patch | sudo git apply -v`

The error output is:
```
Checking patch src/cryptonote_core/tx_pool.cpp...
error: while searching for:
    LockedTXN lock(m_blockchain);
```

    auto sorted_it = m_txs_by_fee_and_receive_time.begin();
    while (sorted_it != m_txs_by_fee_and_receive_time.end())
    {
      txpool_tx_meta_t meta = m_blockchain.get_txpool_tx_meta(sorted_it->second);
      LOG_PRINT_L2("Considering " << sorted_it->second << ", size " << meta.blob_size << ", current block size " << total_size << "/" << max_total_size << ", current coinbase " << print_money(best_coinbase));

```
error: patch failed: src/cryptonote_core/tx_pool.cpp:863
error: src/cryptonote_core/tx_pool.cpp: patch does not apply
```

Annotation: The bin folder of monero under `/usr/local/src/monero/build/release/bin` is not existing.

Running `sudo systemctl status monero` shows the daemon is not running:
```
● monero.service - Monero Daemon
   Loaded: loaded (/lib/systemd/system/monero.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mi 2018-05-09 10:50:49 UTC; 43min ago
  Process: 1603 ExecStart=/usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --detach --restricted-rpc (code=exited, status=203/EXEC)
```

```
Mai 09 10:50:48 eu systemd[1]: monero.service: Unit entered failed state.
Mai 09 10:50:48 eu systemd[1]: monero.service: Failed with result 'exit-code'.
Mai 09 10:50:49 eu systemd[1]: monero.service: Service hold-off time over, scheduling restart.
Mai 09 10:50:49 eu systemd[1]: Stopped Monero Daemon.
Mai 09 10:50:49 eu systemd[1]: monero.service: Start request repeated too quickly.
Mai 09 10:50:49 eu systemd[1]: Failed to start Monero Daemon.
```

Does anyone has any idea? This problem prevents running the pool.

**Comment by MoneroOcean** [comment]
IT is because monero sources were changed and Snipa's patch needs to be updated. I put fix. Can you please check if it solves the issue?

**Comment by mxjoe** [comment]
Thanks for your fast help. This time patching seemed to work:
`Checking patch src/cryptonote_core/tx_pool.cpp...
Applied patch src/cryptonote_core/tx_pool.cpp cleanly.`

The next step `sudo make -j$(nproc)` resulted in an error but currently I am not sure if this is just because I started the command isolated an not within the deployment.bash process.

mkdir -p build/release
cd build/release && cmake -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=release ../.. && make
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled (using easylogging++)
-- Using OpenSSL include dir at /usr/include
-- Checking for module 'libpcsclite'
--   No package 'libpcsclite' found
-- Could NOT find PCSC (missing:  PCSC_LIBRARY PCSC_INCLUDE_DIR) 
-- Found miniupnpc API version 10
-- Using in-tree miniupnpc
CMake Error at external/CMakeLists.txt:42 (add_subdirectory):
  add_subdirectory given source "miniupnp/miniupnpc" which is not an existing
  directory.


CMake Error at external/CMakeLists.txt:44 (set_property):
  set_property could not find TARGET libminiupnpc-static.  Perhaps it has not
  yet been created.


CMake Error at external/CMakeLists.txt:48 (set_property):
  set_property could not find TARGET libminiupnpc-static.  Perhaps it has not
  yet been created.


-- Looking for libunbound
-- Found libunbound include (unbound.h) in /usr/include
-- Found libunbound shared library
-- Using 64-bit LMDB from source tree
-- Building on x86_64 for native
-- Using C security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using C++ security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using linker security hardening flags:  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- AES support enabled
-- Found Boost Version: 105800
-- Could NOT find Readline (missing:  Readline_INCLUDE_DIR Readline_LIBRARY) 
-- Could not find GNU readline library so building without readline support
-- Found Git: /usr/bin/git
Doxygen: graphviz not found - graphs disabled
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/usr/local/src/monero/build/release/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/monero/build/release/CMakeFiles/CMakeError.log".
Makefile:64: recipe for target 'release-all' failed
make: *** [release-all] Error 1

**Comment by bobbieltd** [comment]
+1 , if you successfully install a pool with MoneroOcean, keep me in touch. Even me, I still don't have courage to try his codes ;).

**Comment by MoneroOcean** [comment]
cryptopool.space is pretty happy to run them as far as I know :)
The last error is from Monero build configuration so it is better to be addressed to monero devs. I can't provide complete support here.

**Comment by mxjoe** [comment]
@MoneroOcean Thanks again for your fast reply. I will try a complete reinstall, if that does not work I will report to the monero devs.
