### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alexmateescu** [MoneroOcean/nodejs-pool#27]
Hi 

I am trying to setup your fork of the pool for a monero pool and i get the below error. the error appears about a minute after the miner started working.

what could it be?

i have followed all the how to and also checked to have the wallet addresses both pool and fee in the db.

Could you help me please?

7|pool     | 2018-05-17 23:59:24:967 +02:00: >>> Trusted=1(4.35%) / Validated=22(95.65%) / Invalid=0(0.00%) / Outdated=0(0.00%) / Throttled=0(0.00%) / Total=23 shares
3|worker   | 2018-05-17 23:59:34:362 +02:00: Starting stats collection for 1575017 height
3|worker   | 2018-05-17 23:59:34:457 +02:00: Processed 0 workers for 0.096 seconds. Pool hashrate is: 1
3|worker   | 2018-05-17 23:59:44:458 +02:00: Starting stats collection for 1575017 height
3|worker   | 2018-05-17 23:59:44:517 +02:00: Processed 0 workers for 0.06 seconds. Pool hashrate is: 1
7|pool     | 2018-05-17 23:59:51:072 +02:00: RangeError: Maximum call stack size exceeded
7|pool     |     at v4 (/home/pool/nodejs-pool/node_modules/request/node_modules/uuid/v4.js:4:12)
7|pool     |     at new Multipart (/home/pool/nodejs-pool/node_modules/request/lib/multipart.js:10:19)
7|pool     |     at new Request (/home/pool/nodejs-pool/node_modules/request/request.js:124:21)
7|pool     |     at request (/home/pool/nodejs-pool/node_modules/request/index.js:53:10)
7|pool     |     at Function.post (/home/pool/nodejs-pool/node_modules/request/index.js:61:12)
7|pool     |     at /home/pool/nodejs-pool/lib/remote_comms.js:12:25
7|pool     |     at /home/pool/nodejs-pool/node_modules/async/dist/async.js:2937:44
7|pool     |     at apply (/home/pool/nodejs-pool/node_modules/async/dist/async.js:21:25)
7|pool     |     at /home/pool/nodejs-pool/node_modules/async/dist/async.js:56:12
7|pool     |     at Request._callback (/home/pool/nodejs-pool/lib/remote_comms.js:16:28)
7|pool     |     at self.callback (/home/pool/nodejs-pool/node_modules/request/request.js:185:22)
7|pool     |     at emitOne (events.js:116:13)
7|pool     |     at Request.emit (events.js:211:7)
7|pool     |     at Request.init (/home/pool/nodejs-pool/node_modules/request/request.js:231:17)
7|pool     |     at new Request (/home/pool/nodejs-pool/node_modules/request/request.js:127:8)
7|pool     |     at request (/home/pool/nodejs-pool/node_modules/request/index.js:53:10)
PM2        | App [pool] with id [7] and pid [6546], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:pool id:7

**Comment by MoneroOcean** [comment]
I guess it is same as these:

https://github.com/Snipa22/nodejs-pool/issues/108
https://github.com/Snipa22/nodejs-pool/issues/136
https://github.com/Snipa22/nodejs-pool/issues/238
