### ISSUE TITLE
Alternate Coins Implementation in this pool

### ISSUE THREAD

**Issue by HamzaYasin1** [MoneroOcean/nodejs-pool#29]
Hi,
I'm curious to use this pool for 5 of different cryptonote based coins.
which includes:
XDN
Bitsum
Dero
BCN
Karbo

Please give some advice to put them in the pool,
I've successfully deployed this pool on the server for monero but need to know about alternate coins implementation and one more thing , if we can implement them in the pool so should we use all of them coins on parallel basis in a single pool.
Thanks

**Comment by MoneroOcean** [comment]
Unfortunately due to limited amount of time I can not provide generic guidance for free. Specific questions are OK.

**Comment by HamzaYasin1** [comment]
@MoneroOcean Okay just guide me one thing is it possible to implement all these type of coins within this pool ? 
And how can i see the status that my pool is running.
Thanks

**Comment by bobbieltd** [comment]
Both of your questions : No
Run one coin pool at first.
Come back in a month.

**Comment by MoneroOcean** [comment]
Bobbie is always laser clear :)

**Comment by bobbieltd** [comment]
@sevendoorknobs Cool ! This repo fork is the best fork. Did you deploy it ? Or just thinking ?

**Comment by mannie65** [comment]
@MoneroOcean - I would like to see if you can (Paid) help me with something similar. What's the best way we can talk ?

**Comment by MoneroOcean** [comment]
@mannie65 drop me email to support@moneroocean.stream
