### ISSUE TITLE
longRunner blockID variable type error

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#3]
Hi MonerOcean,

   When you have time, could you please take a look at the Snipa's code to see why we got longRunner errors : 
1. nodejs-pool/lib/local_comms.js : 
function (lastBlock, difficulty, callback) {
                let shareCount = 0;
                let pplnsFound = false;
                let blockList = [];
                console.log("Scanning from: "+lastBlock + " for more than: " + difficulty + " shares");
                range.range(0, lastBlock+1).forEach(function (blockID) {
                    blockID = (blockID - lastBlock+1) * -1;
                    if (blockID < 0){
                        return;
                    }
                    debug("Scanning block: " + blockID);
                    let txn = global.database.env.beginTxn({readOnly: true});
                    let cursor = new global.database.lmdb.Cursor(txn, global.database.shareDB);
                    for (let found = (cursor.goToRange(blockID) === blockID); found; found = cursor.goToNextDup()) {
                        if (pplnsFound){

2. The tweak that doesn't work : blockID = Number((blockID - lastBlock+1) * -1); 

3. The tweak that works : cursor.goToRange(parseInt(blockID))

4. Error message :   Error: You specified keyIsUint32 on the Dbi, so you can't use other key types with it.
at /home/monero/nodejs-pool/lib/local_comms.js:638:46
at Array.forEach () ....

Snipa is busy at the moment. I hope you can help. Thank you.

**Comment by MoneroOcean** [comment]
I do not see this error, so can you try this on your side?

Change this line in cleanShareDB function of local_comms.js:

`for (let found = (cursor.goToRange(blockID) === blockID); found; found = cursor.goToNextDup()) {`

To:

`for (let found = (cursor.goToRange(blockID->Uint32Value()) === blockID); found; found = cursor.goToNextDup()) {`

**Comment by MoneroOcean** [comment]
Ah, noticed that you found a fix your self. The problem is apparently because LMDB nodejs bindings added more strict check https://github.com/Venemo/node-lmdb/commit/953a6d54b3fec08a3dc0e3c1503df4a878728a06 not so long ago:

`+    if (dw->keyType == NodeLmdbKeyType::Uint32Key && keyType != NodeLmdbKeyType::Uint32Key) {
+        return Nan::ThrowError("You specified keyIsUint32 on the Dbi, so you can't use other key types with it.");
+    }`

**Comment by bobbieltd** [comment]
Thank you for shine my mind :+1:  I think you are correct. It's because normal Javascript integer is signed and not uint32. I tried your suggest to convert blockID to uint32 but it didn't work. Here is the error log : 
2017-12-29 20:43 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
/home/pooldaemon/nodejs-pool/lib/local_comms.js:638
                    for (let found = (cursor.goToRange(blockID->Uint32Value()) === blockID); found; found = cursor.goToNextDup()) {
                                                               ^

SyntaxError: Unexpected token >
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /home/pooldaemon/nodejs-pool/init.js:51:17
    at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)

I think parseInt function in Javascript does not return uint32 so it's not a real solution. Is there any other way to convert an integter to uint32 ?

**Comment by bobbieltd** [comment]
I tried : blockID = blockID->Uint32Value(); It doesn't work either;

**Comment by bobbieltd** [comment]
I tried change blockID type to int unsigned in database. Error uint32 still happened.

**Comment by bobbieltd** [comment]
Forgot to tell you, it happens with NVM 8.9.3. You use old NVM 6.9.2 so you don't see this error.  Any new clue ;) ?

**Comment by MoneroOcean** [comment]
Can you like put console.log((typeof blockID).toString()); before this line
to make sure all blockID are "number"?

**Comment by MoneroOcean** [comment]
Anyway your workaround of parseInt(...) looks like a good idea. I'm not
sure why it works since parseInt for "number" should not change nor type
not value of number:

user@localhost:~/nodejs-pool$ cat 1.js
let a = 1;
let b = parseInt(a);
console.log((typeof a).toString());
console.log((typeof b).toString());
console.log(b.toString());

user@localhost:~/nodejs-pool$ node 1.js
number
number
1

**Comment by bobbieltd** [comment]
Only possible explanation for this is that Javascript integer sometimes triggers uint32 wrong type. Here it's is : 
![log debug uint32](https://user-images.githubusercontent.com/29669374/34448322-c693e52a-ed1e-11e7-8c95-9920f7befbe9.png)

![uint32 error](https://user-images.githubusercontent.com/29669374/34448326-cdf3be12-ed1e-11e7-85b0-4ba2a5352b73.png)

**Comment by MoneroOcean** [comment]
Actually can be a bug in node-lmdb code.

**Comment by bobbieltd** [comment]
I’ve just tested with lastest nvm 9.3.0. Same errors with 8.9.3.
So two choice :
Option 1 (I highly advise this) : downgrade to nvm 6.9.2 like other stable long run pools.
Option 2 (put parseInt(blockID), I really don’t think it’s good idea) : unknown and unexpected future uint32 errors.

Thank you for your help and your time. I close the issue.

**Comment by bobbieltd** [comment]
Here is the finding of CoinLogic at Snipa’s repo. It looks logic. Height must not be negative.
![fcc37673-7ce2-4ad7-9b01-e090bf18e94a](https://user-images.githubusercontent.com/29669374/35127192-807773de-fce3-11e7-9ca4-6633ca187b9d.png)

**Comment by MoneroOcean** [comment]
Merged fix to this fork as well.
