### ISSUE TITLE
Getting profitability data from API

### ISSUE THREAD

**Issue by cryptoprofitswitcher** [MoneroOcean/nodejs-pool#30]
I'm developing a profit switcher for cryptonight coins and pools and I would like to integrate MoneroOcean to my app. Therefore I need a way to estimate the profit per day in us dollar with a specified hash rate.

I looked at your [API ](https://api.moneroocean.stream/pool/stats )and found the following data:

```
 "activePortProfit": 0.000007890717962390947,
 "price": {
            "usd": 163.619,
            "eur": 138.690728466
    }
```
I'm assuming that this will help me but what exactly is the value from "activePortProfit" representing?
Can you help me to calculate an estimated profit in us dollar per day based on a specified hash rate?

**Comment by MoneroOcean** [comment]
activePortProfit is estimated profit in XMR for 1 submitted hash, so just multiply that to your hashrate (and multiply with price.usd/eur if required).

**Comment by MoneroOcean** [comment]
Yes. It is profit for 1 H/s. sorry for confusion.
