### ISSUE TITLE
Aeon fork, cannot send payments

### ISSUE THREAD

**Issue by DurinsMine** [MoneroOcean/nodejs-pool#36]
Hello :) I forked Aeon and have everything running. Pool runs okay, can find blocks, balances change. I have one last problem that I cannot solve.

No matter what I put for the balances or payments it always fails with 

This is the output from the wallet
2018-06-18 13:58:45.853 [RPC0] ERROR wallet.wallet2 src/wallet/wallet2.cpp:6315 !scanty_outs.empty(). THROW EXCEPTION: error::not_enough_outs_to_mix
2018-06-18 13:58:45.868 [RPC0] WARN net.http src/wallet/wallet_errors.h:794 /home/pooldaemon/durinscoin/src/wallet/wallet2.cpp:6315:N5tools5error22not_enough_outs_to_mixE: not enough outputs to use, ring size = 2, scanty_outs:
9.000000000000 - 1
0.800000000000 - 1
0.600000000000 - 1
70.000000000000 - 1
0.020000000000 - 1

Payments module error

payments > 2018-06-19 13:00 +00:00: Issue making payments{"code":-19,"message":"not enough outputs to use Please use sweep_dust."}     

payments > Will not make more payments until the payment daemon is restarted!               

I tried to do sweep_unmixable in pools wallet and sweep_all 1 mywallet to get it to work but nothing helps.

I am not sure if it something to do with the coin or the pool isn't set up to send that many coins or something?

I set the max coins per transaction to something really low and have 1 payee per and still not enough output errors

Have over 10,000 coins in the wallet from 70 per block reward and I just cannot get coins to send.
Not sure if this is the best place to ask?

Is this something I need to fix with the coin or does anyone know of a workaround some how?
I am going to try send all the coins from the pool wallet to a new one and see if that works from there.
But even so when a new pool opens, they are never going to be able to make payouts. 

How are outputs made? This is blockchain starting from height 0 not a real fork.

**Comment by bobbieltd** [comment]
🤔 Can you specify the amount that you sent ? Does the error happens immediately or after how much time (coutinh from the time that payment is executed ) ?

**Comment by DurinsMine** [comment]
It is around 70 coins, the block reward is 70, when the pool first starts, it builds up a lot of blocks one after the other as I am the only one mining really and a couple of the nodes.

When it gets time to pay after 60 blocks, I get the not enough outputs error. If I send some coins to another wallet then switch the pool to that and reset the balances on the pool I can get some small payments to go out but after that not enough output errors again.

The error happens when the payments module tries to send the coins through RPC. 

The pools wallet is full of 70 coin block rewards so those are the only unspent outputs?

**Comment by bobbieltd** [comment]
I am not well enough in understanding C++ coin codes. I guess MoneroOcean has better picture. In the mean time of waiting his response.
Here are my opinions :
1. The problem is with the coin and the coin is small / new.
2. The amount you sent is big and is unmixable with other outputs (with other transactions not your own) ( at this point I don’t understand much about ouputs mixing mechanism.
3. You can use temporary solution by reducing max transaction amount in mysql (I don’t remember precise variable name) in short term.

I’m pleased to hear if I say something wrong (because they are just my guesses)

**Comment by DurinsMine** [comment]
I tried to set the max payees to 1, max coins to 1 still same error :(
I am still trying to learn about the outputs and mixing as well

If I make the payments small in the pool then it works fine but not with large transactions

**Comment by MoneroOcean** [comment]
Can't commend anything about Aeon. Not enough experience with this coin.

**Comment by sevendoorknobs** [comment]
Try using the --sweep-all call, that should clear the dust (which is too small to send) and allow the transaction to go through.
