### ISSUE TITLE
Switching coin mechanism

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#37]
Sorry because I haven’t dig thousand of code lines to answer for myself.
When the pool is mining a coin but in the time of mining (no block found yet), there is a new coin that is more profitable, will the pool switch or it will continue to mine the old coin up to block found ?

**Comment by MoneroOcean** [comment]
It will switch immediately.

**Comment by bobbieltd** [comment]
Sorry, forgot to close. Thanks for info.
