### ISSUE TITLE
user scripts

### ISSUE THREAD

**Issue by itsmylife44** [MoneroOcean/nodejs-pool#39]
Hey , thanks for the top work that you are doing , so now i need a help , i try to use  your 

ban_user.js but if i try to start it  ex : node ban_user.js WALLET  , is comming this error : 

Please specify user address to ban

so , how i can specific the wallet and reason ? 

ty

**Comment by MoneroOcean** [comment]
Hi!

It is specified using command line args, like this: `node ban_user.js --user=WALLET --reason="reason explanation"`

**Comment by MoneroOcean** [comment]
P.S. Bans are not immediate and will work only banned user will try to login pool again (or pool module is restarted).  Existing banned user connections are not broken.
