### ISSUE TITLE
Migration from Snipa’s repo to MoneroOcean’s repo

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#4]
As I see in your code, you changed both code and database. Your repo is more active than Snipa’s and I’d like to migrate to yours. Must I reinstall my pool from scratch ? Is there a way to backup mysql and restore to the new one ? What about lmdb data about miners’ history , will I lose them ?

**Comment by MoneroOcean** [comment]
All DB formats are compatible (and will be in future), so you can just update nodejs sources by switching to my fork: `git remote set-url origin https://github.com/MoneroOcean/nodejs-pool.git`

Please aware that sometimes I commit changes and test them in the field after commit so to avoid any issue please wait at least for one day before applying them.

**Comment by MoneroOcean** [comment]
Also please be aware that I commented out admin html api code (do not use it since it is not functional and only add extra security risk).

**Comment by bobbieltd** [comment]
Cool, it’s first time I practice to change source and remote upstream. I successfully migrate my pool from Snipa’s repo to yours without any problems. Thank you alot. I’m on board, CryptoOcean ships 👍👍👍. Hope that I can contribue something to your repo development later, I’m quite noob with coding ( I’m not IT guy). Again, thanks.

**Comment by MoneroOcean** [comment]
Welcome)
