### ISSUE TITLE
longRunner stuck on an old block

### ISSUE THREAD

**Issue by sevendoorknobs** [MoneroOcean/nodejs-pool#42]
Longrunner will not scan past a very old block, no idea why. I have tried locking, unlocking, etc.

**Comment by sevendoorknobs** [comment]
Seems to be an orphaned block causing the issues.

**Comment by sevendoorknobs** [comment]
Was able to run the "block_unlock_without_pay.js" on the orphan block hash and it resolved the issue. WOOHOO!

**Comment by MoneroOcean** [comment]
Yeah. Normally it should not happen in current pool codes (block is unlock after it is marked as orphan  this was fixed by Snipa half and year ago or so). Likely you had orphan that happened long ago?
