### ISSUE TITLE
Queue is growing and eventually crashes the pool

### ISSUE THREAD

**Issue by sevendoorknobs** [MoneroOcean/nodejs-pool#43]
Currently "Queue debug state: 1407 items in the queue 192 items being processed" and they continue to pile up.

**Comment by sevendoorknobs** [comment]
Seems like longRunner is getting stuck attempting to clean the shares and will not continue, causing the queue to backup and the pool to eventually crash.

**Comment by MoneroOcean** [comment]
It is from pool module output? If yes the problem is that your remote share API endpoint is not working correctly (served by remoteShare module).

**Comment by sevendoorknobs** [comment]
The remoteShare module is not the issue, it's the longRunner. It get's stuck when cleaning and causes the rest of the processes to be put on hold I disabled the share cleaner and the issue resolved. Working towards a more permanent solution. 

I am now dealing with blocks being marked as orphans, however, since I am adding new coins to the pool, I think it's just a json response issue.

**Comment by MoneroOcean** [comment]
Can you please copy paste longRunner log output here?

**Comment by sevendoorknobs** [comment]
Yes I will get one shortly.

Also, what determines if a block is an "altBlock"?

**Comment by MoneroOcean** [comment]
If it was mined from daemon port that is not equal to pool.daemon.port.

**Comment by sevendoorknobs** [comment]
Thank ya.

Here are the output - 
`6|longRunn | 2018-07-03 14:37 +00:00: Database Worker: LMDB Env Initialized.
6|longRunn | 2018-07-03 14:37 +00:00: Cleaning up the share DB
6|longRunn | 2018-07-03 14:37 +00:00: Getting oldest block on alternate chain
6|longRunn | 2018-07-03 14:37 +00:00: Getting oldest block on main chain
6|longRunn | 2018-07-03 14:37 +00:00: There are no locked blocks in the system.                                      Woohoo!
6|longRunn | 2018-07-03 14:37 +00:00: Cleaning up the cache DB
6|longRunn | 2018-07-03 14:37 +00:00: Deleted cache items: 0
6|longRunn | 2018-07-03 14:37 +00:00: Scanning from: 1564936 for more than: 2244                                     89244584 shares
6|longRunn | 2018-07-03 14:37 +00:00: Found the first block to be deleted at 156                                     4731 height

6|longRunn | 2018-07-03 14:38 +00:00: Scan finished
6|longRunn | 2018-07-03 14:38 +00:00: Block cleaning started: removing 45146 block share records
`

**Comment by sevendoorknobs** [comment]
Thank! Here is the longRunner output.

> 6|longRunn | 2018-07-03 14:37 +00:00: Database Worker: LMDB Env Initialized.
> 6|longRunn | 2018-07-03 14:37 +00:00: Cleaning up the share DB
> 6|longRunn | 2018-07-03 14:37 +00:00: Getting oldest block on alternate chain
> 6|longRunn | 2018-07-03 14:37 +00:00: Getting oldest block on main chain
> 6|longRunn | 2018-07-03 14:37 +00:00: There are no locked blocks in the system.                                      Woohoo!
> 6|longRunn | 2018-07-03 14:37 +00:00: Cleaning up the cache DB
> 6|longRunn | 2018-07-03 14:37 +00:00: Deleted cache items: 0
> 6|longRunn | 2018-07-03 14:37 +00:00: Scanning from: 1564936 for more than: 2244                                     89244584 shares
> 6|longRunn | 2018-07-03 14:37 +00:00: Found the first block to be deleted at 156                                     4731 height
> 
> 6|longRunn | 2018-07-03 14:38 +00:00: Scan finished
> 6|longRunn | 2018-07-03 14:38 +00:00: Block cleaning started: removing 45146 block share records

**Comment by MoneroOcean** [comment]
No issues in the longRunner logs. There "Currently "Queue debug state: 1407 items in the queue 192 items being processed" and they continue to pile up." comes from?

**Comment by sevendoorknobs** [comment]
It does not progress past the "Block cleaning started" stage.

That is the response from the pool "queue" if I turn block cleaner back on, it get's stuck and the queue builds up until it runs out of pages and crashes. However, with block cleaner off, it works fine. It also seems like "altblocks" aren't storing properly, which may be related.

**Comment by sevendoorknobs** [comment]
Still no bueno. It doesn't want to run.

**Comment by MoneroOcean** [comment]
Looks like the possible issue is in the number of blocks it tries to clean at once. Will patch it today to see if it will help.

**Comment by sevendoorknobs** [comment]
Man, you are much better than I am! haha!

That worked and did not cause any issues!
