### ISSUE TITLE
Active Port and Daemon Port are the same, still seen as alt blocks.

### ISSUE THREAD

**Issue by sevendoorknobs** [MoneroOcean/nodejs-pool#44]
Title says it all. Due to this, shares are reporting incorrectly and block cleaner does not work.

**Comment by MoneroOcean** [comment]
Not sure I can help unless you put more logs. Like SQL dump of pool params and pool module logs there it submits some blocks like altblocks.

**Comment by sevendoorknobs** [comment]
Your last commit fixed the block cleaner, thank you and good job.

I am working on the port/altblock situation. Currently effort is reporting as 0 and roundshares are as well, any ideas?

**Comment by MoneroOcean** [comment]
Still need more logs to do any meaningful conclusions. Like SQL dump of pool params and pool module logs there it submits some blocks like altblocks.

**Comment by MoneroOcean** [comment]
Closed until more logs are provided.
