### ISSUE TITLE
transfer_split issue

### ISSUE THREAD

**Issue by alexmateescu** [MoneroOcean/nodejs-pool#46]
hi guys 

if i try to change the transfer func to transfer_split here is the answer ai am getting from the wallet.

11|payment | 2018-07-08 13:09:33:985 +03:00: Unknown error from the wallet: {"amount_list":[1617070000000],"fee_list":[137045640],"multisig_txset":"","tx_hash_list":["a337f500c9b56f8deecc40ebf318f2b184910060f5a1b0e30e75f87ae7c702c9"]}

what could be the issue?

**Comment by MoneroOcean** [comment]
Likely different output is produced by wallet API and pool support should be updated to take that into account:
https://getmonero.org/resources/developer-guides/wallet-rpc.html#transfer_split
https://getmonero.org/resources/developer-guides/wallet-rpc.html#transfer

**Comment by alexmateescu** [comment]
you can see the 2 answers below. never mind the coin. the coin is monero identical and the same. just names changed and amounts. wallet is monero v12

the transfer_split rpc and answer

11|payment | 2018-07-08 13:09:33:983 +03:00: { id: '0',
11|payment |   jsonrpc: '2.0',
11|payment |   result: 
11|payment |    { amount_list: [ 1617070000000 ],
11|payment |      fee_list: [ 137045640 ],
11|payment |      multisig_txset: '',
11|payment |      tx_hash_list: 
11|payment |       [ 'a337f500c9b56f8deecc40ebf318f2b184910060f5a1b0e30e75f87ae7c702c9' ] } }
11|payment | 2018-07-08 13:09:33:984 +03:00: { amount_list: [ 1617070000000 ],
11|payment |   fee_list: [ 137045640 ],
11|payment |   multisig_txset: '',
11|payment |   tx_hash_list: 
11|payment |    [ 'a337f500c9b56f8deecc40ebf318f2b184910060f5a1b0e30e75f87ae7c702c9' ] }
11|payment | { destinations: 
11|payment |    [ { amount: 1503780000000,
11|payment |        address: 'ZYZXZiWS9dPRjcw6wKpg924znS7Y6BbhaZFgjCExUymRSztiKaxnVmaAFBTRwGSSa7MWbMw6iUzqr9zFRw8p4Y7JiFkiJFTSpm4' },
11|payment |      { amount: 113290000000,
11|payment |        address: 'ZYZXZj6s3nQQ3yL6MjYqjCGjKQMe1LNRX5ABvRM8RNorizxcgow5PG83CXyA7KprMGit73Uu4bojoUkGa2GyV28Z6qpcbsbWMWU' } ],
11|payment |   priority: 0,
11|payment |   mixin: 8,
11|payment |   get_tx_key: true,
11|payment |   new_algorithm: true }
11|payment | 2018-07-08 13:09:33:985 +03:00: Unknown error from the wallet: {"amount_list":[1617070000000],"fee_list":[137045640],"multisig_txset":"","tx_hash_list":["a337f500c9b56f8deecc40ebf318f2b184910060f5a1b0e30e75f87ae7c702c9"]}


and the regular one

11|payment | 2018-07-08 13:10:36:609 +03:00: { id: '0',
11|payment |   jsonrpc: '2.0',
11|payment |   result: 
11|payment |    { amount: 1617070000000,
11|payment |      fee: 137045480,
11|payment |      multisig_txset: '',
11|payment |      tx_blob: '',
11|payment |      tx_hash: '57897092ba2913e411f6e871da70a6aff3dba6ec0e1021024f29ebe612e49b11',
11|payment |      tx_key: '6feacd95d5e1ead702352bf2ee195f38dded08735b4479e56fcdc8085ae14f08',
11|payment |      tx_metadata: '' } }
11|payment | 2018-07-08 13:10:36:610 +03:00: { amount: 1617070000000,
11|payment |   fee: 137045480,
11|payment |   multisig_txset: '',
11|payment |   tx_blob: '',
11|payment |   tx_hash: '57897092ba2913e411f6e871da70a6aff3dba6ec0e1021024f29ebe612e49b11',
11|payment |   tx_key: '6feacd95d5e1ead702352bf2ee195f38dded08735b4479e56fcdc8085ae14f08',
11|payment |   tx_metadata: '' }
11|payment | 2018-07-08 13:10:36:611 +03:00: { destinations: 
11|payment |    [ { amount: 113290000000,
11|payment |        address: 'ZYZXZj6s3nQQ3yL6MjYqjCGjKQMe1LNRX5ABvRM8RNorizxcgow5PG83CXyA7KprMGit73Uu4bojoUkGa2GyV28Z6qpcbsbWMWU' },
11|payment |      { amount: 1503780000000,
11|payment |        address: 'ZYZXZiWS9dPRjcw6wKpg924znS7Y6BbhaZFgjCExUymRSztiKaxnVmaAFBTRwGSSa7MWbMw6iUzqr9zFRw8p4Y7JiFkiJFTSpm4' } ],
11|payment |   priority: 0,
11|payment |   mixin: 8,
11|payment |   get_tx_key: true }
11|payment | 2018-07-08 13:10:36:612 +03:00: [**] Successful payment to ZYZXZj6s3nQQ3yL6MjYqjCGjKQMe1LNRX5ABvRM8RNorizxcgow5PG83CXyA7KprMGit73Uu4bojoUkGa2GyV28Z6qpcbsbWMWU for 113.29 MTUX (fee 0)
11|payment | 2018-07-08 13:10:36:612 +03:00: [**] Successful payment to ZYZXZiWS9dPRjcw6wKpg924znS7Y6BbhaZFgjCExUymRSztiKaxnVmaAFBTRwGSSa7MWbMw6iUzqr9zFRw8p4Y7JiFkiJFTSpm4 for 1503.78 MTUX (fee 0)
11|payment | 2018-07-08 13:10:36:612 +03:00: [*] Successful payment to multiple miners of 1617.07 MTUX (fee 0 - 0.13704548 = -0.13704548) with tx_hash 57897092ba2913e411f6e871da70a6aff3dba6ec0e1021024f29ebe612e49b11 and tx_key 6feacd95d5e1ead702352bf2ee195f38dded08735b4479e56fcdc8085ae14f08
11|payment | 2018-07-08 13:10:36:613 +03:00: Payment queue drained

**Comment by bobbieltd** [comment]
The error you got when using transfer_spit is from Snipa’s dust check. You can fix it by replace all if (body.fee && body.fee > 10) —> if (body.fee_list && body.fee_list > 10) in xmr.js/coin.js in payment directory.

**Comment by bobbieltd** [comment]
!Remind me in a month 🐶

**Comment by MoneroOcean** [comment]
Sorry guys, will put this into low priority at this moment. Have more pressing thing to put effort now (xmrig fork).

**Comment by alexmateescu** [comment]
found the solution for this. i have added under paymentDetails priority 2 and also changed the payment processing function. i'll put a link with the complete changes once i am done testing.

**Comment by bobbieltd** [comment]
Sorry, Github doesn’t have Remind function. How are you going ? Keep trying or abandoned ?

**Comment by alexmateescu** [comment]
this is fixed as far as i am concerned.
