### ISSUE TITLE
dublicate job

### ISSUE THREAD

**Issue by 1rV1N-git** [MoneroOcean/nodejs-pool#5]
Hello i think there is need to add code to prevent send duplicate job.

function newBlockTemplate(template) {
   let buffer = new Buffer(template.blocktemplate_blob, 'hex');
    let previous_hash = new Buffer(32);
    buffer.copy(previous_hash, 0, 7, 39);
    console.log(threadName + 'New block to mine at height: ' + template.height + '.  Difficulty: ' + template.difficulty);
    if (activeBlockTemplate) {
		**if (activeBlockTemplate.previous_hash.toString('hex') === template.prev_hash ) {
			console.log(threadName + "Same job");
			return;
		}**
		pastBlockTemplates.enq(activeBlockTemplate);
	}
	activeBlockTemplate = new BlockTemplate(template);
	console.log(threadName + "Update workers");
    for (let minerId in activeMiners) {
        if (activeMiners.hasOwnProperty(minerId)) {
            let miner = activeMiners[minerId];
            debug(threadName + "Updating worker " + miner.payout + " With new work at height: " + template.height);
            miner.sendNewJob();
        }
    }
}

  
example:
**1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 4 - 63492) New block to mine at height: 42585.  Difficulty: 75447651**
1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 4 - 63492) activeBlockTemplate : 1cd23e23e48d238c57e536a8aac2817220ee6be70fad8b5b3c79279ae8515d09
1|pool     | (Worker 4 - 63492) 7062b336bc841d0d0dea6b09e94bf3b3d42371019252dbf1dbd8fdaff5af2140
1|pool     | (Worker 4 - 63492) Update workers
1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 1 - 63474) New block to mine at height: 42585.  Difficulty: 75447651
1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 1 - 63474) activeBlockTemplate : 1cd23e23e48d238c57e536a8aac2817220ee6be70fad8b5b3c79279ae8515d09
1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 1 - 63474) 7062b336bc841d0d0dea6b09e94bf3b3d42371019252dbf1dbd8fdaff5af2140
1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 1 - 63474) Update workers
1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 2 - 63480) New block to mine at height: 42585.  Difficulty: 75447651
1|pool     | (Worker 2 - 63480) activeBlockTemplate : 1cd23e23e48d238c57e536a8aac2817220ee6be70fad8b5b3c79279ae8515d09
1|pool     | (Worker 2 - 63480) 7062b336bc841d0d0dea6b09e94bf3b3d42371019252dbf1dbd8fdaff5af2140
1|pool     | (Worker 2 - 63480) Update workers
1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 3 - 63486) New block to mine at height: 42585.  Difficulty: 75447651
1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 3 - 63486) activeBlockTemplate : 1cd23e23e48d238c57e536a8aac2817220ee6be70fad8b5b3c79279ae8515d09
1|pool     | (Worker 3 - 63486) 7062b336bc841d0d0dea6b09e94bf3b3d42371019252dbf1dbd8fdaff5af2140
1|pool     | (Worker 3 - 63486) Update workers
1|pool     | 2018-01-05 21:18:22 +00:00: (Master) New block to mine at height: 42585.  Difficulty: 75447651
1|pool     | 2018-01-05 21:18:22 +00:00: (Master) activeBlockTemplate : 1cd23e23e48d238c57e536a8aac2817220ee6be70fad8b5b3c79279ae8515d09
1|pool     | (Master) 7062b336bc841d0d0dea6b09e94bf3b3d42371019252dbf1dbd8fdaff5af2140
**1|pool     | 2018-01-05 21:18:22 +00:00: (Worker 4 - 63492) New block to mine at height: 42585.  Difficulty: 75447651**
1|pool     | (Worker 4 - 63492) activeBlockTemplate : 7062b336bc841d0d0dea6b09e94bf3b3d42371019252dbf1dbd8fdaff5af2140
1|pool     | (Worker 4 - 63492) 7062b336bc841d0d0dea6b09e94bf3b3d42371019252dbf1dbd8fdaff5af2140
**1|pool     | (Worker 4 - 63492) Same job**
1|pool     | 2018-01-05 21:18:22 +00:00: (Master) Update workers

**Comment by MoneroOcean** [comment]
OK. I never looked into this code, so it will take time for me to completely understand what is going on here and if fix is helpful. If not yet already done I recommend to submit same issue against main repo too.

**Comment by MoneroOcean** [comment]
Actually I do not think it is a problem here and moreover fix will lead to harmful effect. Fix rejects new block template if hash of previous block is the same as hash of previous block of active block template, right? This is not right, since monerod can provide updated valid block templates with the same previous block hash (for example if height is not changed and there are new transaction included into block template). This fix will merely allows the first block template to be used for each height and will reject their valid updates that can lead to lower block rewards (because less tx fees are included).

Hope it make sense. Feel free to point me if I'm wrong here.

**Comment by 1rV1N-git** [comment]
Ok, I understood you. I did not know it could be that way.
There you can compare by blocktemplate_blob or maybe it's worth it just to put a temporary restriction, for example in 2 seconds.

**Comment by 1rV1N-git** [comment]
I want to revent this 
![image](https://user-images.githubusercontent.com/34376228/34640165-a9894c1e-f2fe-11e7-9b18-93649c7be559.png)

**Comment by bobbieltd** [comment]
@1rV1N-git : Snipa’s repo got same bug like yours before 
See https://github.com/Snipa22/nodejs-pool/issues/198
@MoneroOcean Did you merge the “Duplicate Job” fix from Snipa’s repo ?

**Comment by MoneroOcean** [comment]
Yeah, sure. It was merged on the same day: https://github.com/MoneroOcean/nodejs-pool/commit/6a083229b9c2306330de6a316513daab9da85c6a

**Comment by bobbieltd** [comment]
I got same error "Duplicate jobs" multiple time and Snipa did fix it, no more that errors after that fix. I've never see that errors again from that day.
@MoneroOcean  You didn't merge "Fix for the 300 msec template bug identified by Mayday30."
https://github.com/MoneroOcean/nodejs-pool/blob/master/lib/pool.js#L174 doesn't reflect fix : 
  } else {
           if (repeating !== true) {
                  setTimeout(templateUpdate, 300);
              }
         }
      });
  }

**Comment by MoneroOcean** [comment]
This particular line/fix you mentioned is not related to duplicate jobs. It is fix for frequent block template updates and I decided to rework it after (that is why this line is different). I'm pretty sure in this particular case since actually I'm Mayday30;)

**Comment by 1rV1N-git** [comment]
I use snipa repo wtih Mayday30 fix in Almost all nodes c addition from your repo becase port 3333))
It is so strange becase the screenshot that i send it is pool node by your repo.
 I added this code and I got in log "Same job".
You may add the code without return for debag the error.
In a couple of days I plan to change all node to your repo.

**Comment by bobbieltd** [comment]
For this error, I know the trick to make it happen by running 4 or more xmrig instances at the same time. I’ve runned tests with my newly migrated pool to MO repo. 
It didn’t get any “duplicate job” errors. So with me, MO repo is all right. 
Of course, I don’t know if there are other situations which could show this errors.

**Comment by 1rV1N-git** [comment]
This error does not appear so often during normal operation. it always appears when the pool is restarted and when the block is found. the rest of the time one for 30-50 updates of the block template

**Comment by MoneroOcean** [comment]
That is very useful statistics and will help me to narrow down the problem area. But why do not you submit that against main Snipa's repo? I will try to investigate and fix that for course but I think he can do that much more easier (not sure if faster:).

**Comment by 1rV1N-git** [comment]
(not sure if faster:) that is why  )

**Comment by MoneroOcean** [comment]
Looks like I finally managed to get better picture what is going on here. You got the problem right and I was wrong in my first comment about the fact that block template can be updated over time when prev_hash is not changed. Looks like this situation can happen when thread BT update happens before rapid BT update from main thread. In this case newBlockTemplate(...) is called twice (first from worker thread and second from main thread during sendToWorkers({type: 'newBlockTemplate', data: rpcResponse});).

**Comment by MoneroOcean** [comment]
The fix will be very similar to what you suggested.

**Comment by MoneroOcean** [comment]
This should fix this:

https://github.com/MoneroOcean/nodejs-pool/commit/1e8d0a0e2a7c649fc62924a50a587b468fbd7977
https://github.com/MoneroOcean/nodejs-pool/commit/29b6fd7b9215f91b2c0e7b054b6aa6104b732c21
https://github.com/MoneroOcean/nodejs-pool/commit/ac4ea5c52cbe87f743478b46603fd9aef96576ee

**Comment by bobbieltd** [comment]
Thanks. This fix concerns pool.js and xmr.js , if I want to apply the fix, what do I need to do ? 
pm2 stop all
cd ~/nodejs-pool
git pull
pm2 start all
Is that process correct ?

**Comment by MoneroOcean** [comment]
For that fix you only need to restart pool module:

`cd ~/nodejs-pool && git pull && pm2 restart pool`
`pm2 logs pool`

Will do the trick.

**Comment by MoneroOcean** [comment]
xmr.js fixes are not necessary to fix this particular issue but it is related bug fixes.

**Comment by 1rV1N-git** [comment]
Excellent Job!!. Thanks a lot

**Comment by bobbieltd** [comment]
Thank you.
