### ISSUE TITLE
HashFactor / Algo Options

### ISSUE THREAD

**Issue by sevendoorknobs** [MoneroOcean/nodejs-pool#50]
Working with Bytecoin, which has not yet forked and wondering what the best options would be for the HashFactor, and algo settings. The coin functions on CN1, but I think it is causing issues.

**Comment by MoneroOcean** [comment]
HashFactor is only used if you setup pool for multi coin mining. For single coin mining you better leave it as 1. Algo should be empty string ("") as well.
