### ISSUE TITLE
Request separate pool/port for profit switchers

### ISSUE THREAD

**Issue by Pandoraaaaa** [MoneroOcean/nodejs-pool#61]
Hi,

I would like to see a true profit switching pool, meaning only miners with profit switching configured will be on the pool. Also on this separate pool (port) I would like to see algo switch based on true profits without giving xmr 10% advantage. Everyone on the pool would mine the most profitable coin and share the rewards.

Thank you!

**Comment by MoneroOcean** [comment]
I do not see any benefit in doing this. 10% cn/1 algo handicap is only minimize amount of switching. There is also 5% current algo handicap. Guess you will not like if your miners will ping pong algorithms every couple of seconds that will lead to less profits and their likely crashes.
