### ISSUE TITLE
Block template request failed for 18081 port.

### ISSUE THREAD

**Issue by QuantumLeaper** [MoneroOcean/nodejs-pool#65]
When running on testnet (and changing the configurations within MySQL - ports and testnet=true), I seem to get:
Block template request failed for 18081 port. 

(I changed daemon RPC port to run on 18081 on testnet)
Also tried 28081 (default testnet daemon port), same error message:
`[Pool] Block template request failed for 18081 port.`

However, the monero-wallet-cli and monero-wallet-rpc connect to the daemon no problem. It just doesn't seem to be generating a block template?

**Comment by QuantumLeaper** [comment]
Ah, had to update the Monero address in the database from ""

**Comment by Aiden0801** [comment]
Hi. Can I ask you about it if you don't mind? Did you change it to the 127.0.0.1?
I changed the address but still gets that error.
