### ISSUE TITLE
Block detect very slow when restarting pool

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#66]
Here is the log (one coin pool), very slow to have block template (I guess at worker) : 
7|pool  | 2018-09-28 13:12:53:981 +00:00: Invalid miner 8PQqeiKmBM:test (103.7.39.41) [], disconnecting due to: No active block template
7|pool  | 2018-09-28 13:12:59:970 +00:00: Invalid miner 8PQqeiKmBM:test (103.7.39.43) [], disconnecting due to: No active block template
7|pool  | 2018-09-28 13:13:05:991 +00:00: Invalid miner 8PQqeiKmBM:test (103.7.39.46) [], disconnecting due to: No active block template
7|pool  | 2018-09-28 13:13:11:984 +00:00: Invalid miner 8PQqeiKmBM:test (103.7.39.46) [], disconnecting due to: No active block template
7|pool  | 2018-09-28 13:13:17:991 +00:00: Invalid miner 8PQqeiKmBM:test (103.7.39.42) [], disconnecting due to: No active block template
7|pool  | 2018-09-28 13:13:18:922 +00:00: >>> Trusted=0(0.00%) / Validated=0(0.00%) / Invalid=0(0.00%) / Outdated=0(0.00%) / Throttled=0(0.00%) / Total=0 shares
7|pool  | 2018-09-28 13:13:24:009 +00:00: Invalid miner 8PQqeiKmBM:test (103.7.39.46) [], disconnecting due to: No active block template
7|pool  | 2018-09-28 13:13:38:962 +00:00: Did not send e-mail to 'undefined' successfully!  Response: undefined Response: undefined
7|pool  | 2018-09-28 13:13:48:922 +00:00: >>> Trusted=0(0.00%) / Validated=0(0.00%) / Invalid=0(0.00%) / Outdated=0(0.00%) / Throttled=0(0.00%) / Total=0 shares
7|pool  | 2018-09-28 13:14:18:922 +00:00: >>> Trusted=0(0.00%) / Validated=0(0.00%) / Invalid=0(0.00%) / Outdated=0(0.00%) / Throttled=0(0.00%) / Total=0 shares
7|pool  | 2018-09-28 13:14:48:922 +00:00: >>> Trusted=0(0.00%) / Validated=0(0.00%) / Invalid=0(0.00%) / Outdated=0(0.00%) / Throttled=0(0.00%) / Total=0 shares
7|pool  | 2018-09-28 13:14:59:948 +00:00: [*] New block to mine at 438167 height with 150964764 difficulty and 12090 port (with algo hash factor 1)
7|pool  | 2018-09-28 13:15:18:922 +00:00: >>> Trusted=0(0.00%) / Validated=2(100.00%) / Invalid=0(0.00%) / Outdated=0(0.00%) / Throttled=0(0.00%) / Total=2 shares

**Comment by MoneroOcean** [comment]
Likely it is daemon delay. I do not think I can anything better then calling templateUpdate(""); the first thing in worker thread.

**Comment by bobbieltd** [comment]
Thanks for info. I doubt that also, it only happens with one coin.
