### ISSUE TITLE
20 XMR assistance fee for a group

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/nodejs-pool#68]
Is 20 XMR assitance fee applicable if I use the multiple coin closed source codes for multiple pools (not my pools) ? Do I have permission to share codes for other pools ?
If so, I will setup group buying.

**Comment by bobbieltd** [comment]
Reselling possibility ? Haha

**Comment by MoneroOcean** [comment]
For 20 XMR you can use these sources for any pools you like or open source them if you like. But no reselling possibility (have to take your word for it). Source updates, bug fixes are also included into this price. Initial help with one code deployment (if required) is also included.

**Comment by bobbieltd** [comment]
Cool ! So it is a good offer. I will try to persuade other pool owners to fund raising to have the codes. Thanks alot for your great work.
