### ISSUE TITLE
blockManager.js PPS mode is not functioning

### ISSUE THREAD

**Issue by sunxfof** [MoneroOcean/nodejs-pool#7]
After looking at the database, I think there is a typo in blockManager.js

global.config.payout.pps === true

shouble be substituated with
global.config.pps.enable === true

And this will fix the breaking.

**Comment by bobbieltd** [comment]
Does this reflect with config table value ? We just to put true or false in config, aren’t we ?

**Comment by sunxfof** [comment]
True, as the correct item should be config.pps.enable, while config.payout.pss leads nowhere in the mysql database.

**Comment by MoneroOcean** [comment]
Yes, looks like your are right. Put fix (problem was added by me and was not identified since I never used PPS mode):

https://github.com/MoneroOcean/nodejs-pool/commit/9e5217d07d4c0beaa687a9c15d6c171c9ecaadd9

**Comment by sunxfof** [comment]
Thank you, you are doing a great job!

**Comment by bobbieltd** [comment]
Great fix. Thank you both of you.
