### ISSUE TITLE
Pool maximum difficulty

### ISSUE THREAD

**Issue by BKdilse** [MoneroOcean/nodejs-pool#86]
What are your views or experiences in increasing the maxDifficulty in the DB from the default 500000?

Any possible side affects?

Lastly, does this mean a miners difficulty can only reach a maximum of 500000?

**Comment by bobbieltd** [comment]
Feel free to 10x that number , specially on ASIC pools with millions fixed diff. No side effect. The drawback is trusting system cheatable but nothing to worry (it is error margin acceptable).

**Comment by BKdilse** [comment]
Yeah, I've been running it at a higher diff for a while, and most pools seem ok.  I find that the rig results showing up on the pool fluctuates heavily, so a 10kh/s rig goes from 5kh/s to 25kh/s quite often.

Any experience in this behaviour?

**Comment by bobbieltd** [comment]
I have no rigs.
I have some pools with hashrate dancing up and down. I don’t care much. It is because of short block time (for example Dero).
Using small fixed diff can solve flutuating hashrate.

**Comment by BKdilse** [comment]
Ok thanks.
